Confirm password
ArastoSahbaei/cryptoanalysis pull request #108
Opened 2021-11-16 23:08 UTC by tomisek

2021-11-17 10:45 UTC, Tjonsson93 requested changes
When registering a new account , the error (email does already exists) appears when this is not true in database storage.
The newly registered account does infact being saved in the user table in the database, but the "automatic" log in process after registering a new user does not work.

2021-11-17 20:45 UTC, tomisek commented
Changes done

2021-11-18 10:35 UTC, JoakimMalmberg approved these changes

2021-11-18 20:34 UTC, Tjonsson93 approved these changes

2021-11-18 20:34 UTC, merged